# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Apodgram to Firebase

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_firebase:

    runs-on: ubuntu-latest

    steps:
    - name: Cheching Repository
      uses: actions/checkout@v2
    - name: Testing
      run: echo 'Testing'
    - name: Install Node Packages
      run:  npm install
    - name: Build React App
      run:  npm run build
    - name: Deploy Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
